services:
  - type: web
    name: perplexity-backend
    env: python
    region: oregon
    plan: starter
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: OPENAI_API_KEY
        sync: false  # Set this in Render dashboard
      - key: BRAVE_API_KEY
        sync: false  # Set this in Render dashboard
      - key: EXA_API_KEY
        sync: false  # Set this in Render dashboard
      - key: REDIS_URL
        fromService:
          type: redis
          name: perplexity-redis
          property: connectionString

  - type: redis
    name: perplexity-redis
    region: oregon
    plan: starter
    maxmemoryPolicy: allkeys-lru
